### ISSUE TITLE
Auto change in block code causes gutenberg to save revision, and browser alert

### ISSUE THREAD

**Issue by webplantmedia** [EssentialBlocks/countdown-block#1]
Everytime the Gutenberg editor page is refreshed, a new id is generated, causing a revision to be saved, and also a browser alert to popup if you try to navigate away from the page without making a change. See screenshot below.

![2021-02-05_08-45-29](https://user-images.githubusercontent.com/2718748/107049636-f4cd1f80-678f-11eb-8dcf-b13eae0da7ea.jpg)

![2021-02-05_08-49-46](https://user-images.githubusercontent.com/2718748/107049643-f696e300-678f-11eb-9b6d-6f8b5ebda827.jpg)

This is great plugin. Well done! I hope you can get this small bug fixed.

**Comment by tasnimAlam** [comment]
Hi @webplantmedia , thanks for your feedback. Please update to version 1.0.3
